-- local nnoremap = require('grzywn.keymap').nnoremap
--
-- nnoremap('<leader>fa', '<cmd>FlutterRun<cr>')
-- nnoremap('<leader>fq', '<cmd>FlutterQuit<cr>')
-- nnoremap('<leader>fr', '<cmd>FlutterHotReload<cr>')
-- nnoremap('<leader>fR', '<cmd>FlutterHotRestart<cr>')
-- nnoremap('<leader>fD', '<cmd>FlutterVisualDebug<cr>')
